/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/selects/SelectCategory copy.vue')['default']
    Core: typeof import('./src/components/core/Core.vue')['default']
    DialogChoiceCompany: typeof import('./src/components/dialogs/companies/DialogChoiceCompany.vue')['default']
    DialogDelete: typeof import('./src/components/dialogs/DialogDelete.vue')['default']
    DialogLots: typeof import('./src/components/dialogs/lots/DialogLots.vue')['default']
    DialogRegisterAnimal: typeof import('./src/components/dialogs/animals/DialogRegisterAnimal.vue')['default']
    DialogRegisterFarm: typeof import('./src/components/dialogs/farms/DialogRegisterFarm.vue')['default']
    DialogRegisterProducer: typeof import('./src/components/dialogs/producers/DialogRegisterProducer.vue')['default']
    DialogWeighing: typeof import('./src/components/dialogs/animals/DialogWeighing.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/selects/Select.vue')['default']
    SelectAge: typeof import('./src/components/selects/SelectAge.vue')['default']
    SelectCategory: typeof import('./src/components/selects/SelectCategory.vue')['default']
    SelectGender: typeof import('./src/components/selects/SelectGender.vue')['default']
    SelectOrigin: typeof import('./src/components/selects/SelectOrigin.vue')['default']
    SelectStatusAnimal: typeof import('./src/components/selects/SelectStatusAnimal.vue')['default']
    SelectStatusLots: typeof import('./src/components/selects/SelectStatusLots.vue')['default']
    Toasts: typeof import('./src/components/toasts/Toasts.vue')['default']
    VBtntext: typeof import('vuetify/lib')['VBtntext']
    VSw: typeof import('vuetify/lib')['VSw']
  }
}
